openapi: 3.0.0
info:
  title: Sample API for authors and their works 
  version: 1.0.0 
   
servers:
 - url: http://localhost:8088/library
 
paths:
  /authors:
    get:
      summary: Returns a list of all available authors
      responses:
        '200':
          description: A list of all available authors
          content:
            application/json:
             schema:
                type: array
                items:
                  type: object
                  properties:
                    firstname:
                      type: string
                    lastname:
                      type: string
                    age:
                      type: integer
                      
    post:
      summary: Adds an author to the list of available authors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                age:
                  type: integer
      responses:
        '201':
          description: Created
         
  /authors/{workId}:
    get:
      summary: Returns the work of an author with the given id
      parameters:
        - name: workId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A work of an author
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    format: int64
                  name:
                    type: string
                  year:
                    type: integer
        '404':
          description: No work found for given id.
                 
  /authors/author:
    get:
      summary: Returns all works of an author
      parameters:
        - name: firstname 
          in: query
          required: true
          schema:
            type: string
        - name: lastname
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: All works of an author
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int65
                    name:
                      type: string
                    year:
                      type: integer
        '404':
          description: Given author not found       
         